add_newline = true
command_timeout = 200
# format = "[$directory$git_branch$git_status]($style)$character"

format = """
$directory\
$python\
$git_branch\
$git_status\
$fill\
$line_break[ $character ]($style)
"""

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 0
truncate_to_repo = false
# truncation_symbol = "…/"
# repo_root_style = "bold cyan"
# repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

# [git_branch]
# format = "[$branch]($style) "
# style = "italic cyan"

[git_branch]
style = "cyan"
format = ' [\[$symbol$branch\] ]($style)'

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[python]
style = "blue"
symbol=""
pyenv_version_name = true
format = ' [\[$symbol( $virtualenv)\]]($style)'

